### ISSUE TITLE
question

### ISSUE THREAD

**Issue by AcierP** [h0nde/tips-for-python-bot-creators#1]
how are arguments passed with connections in terms of cookies, data etc and how is it possible to parse json from a socket response?

also wont requests.session cause a memory issue when multithreading on a large scale?

**Comment by h0nde** [comment]
Cookies are just headers too, they follow the format of `Cookie: key=value; key2=value2`.

Once you have the full response, you split the headers and it's body, and then parse it using your JSON library of choice (`orjson` being the fastest):
```python
import orjson

# send request and receive response ..

resp, body = resp.split(b"\r\n\r\n", 1)
data = orjson.loads(body)
print(data)
```

The `requests` library can cause all sorts of memory issues, but handling connections probably won't be the cause, since there is a limit on the amount of connecitons it can have open at a time.

**Comment by RoseMAgreement** [comment]
> Cookies are just headers too, they follow the format of `Cookie: key=value; key2=value2`.
> 
> To send data you must specify it's mimetype (`Content-Type`), length (`Content-Length`), and the actual data with a prefix of `b'\r\n\r\n'`
> 
> ```httpspec
> POST / HTTP/1.1
> Host: example.org
> Content-Type: application/json
> Content-Length: 16
> 
> {"key": "value"}
> ```
> 
> Once you have the full response, you split the headers and it's body, and then parse it using your JSON library of choice (`orjson` being the fastest):
> 
> ```python
> import orjson
> 
> # send request and receive response ..
> 
> resp, body = resp.split(b"\r\n\r\n", 1)
> data = orjson.loads(body)
> print(data)
> ```
> 
> The `requests` library can cause all sorts of memory issues, but handling connections probably won't be the cause, since there is a limit on the amount of connecitons it can have open at a time. + I'd recommend using adifferent Session for each thread.

I agree with you h0nda, also i don't think they should use "python" for doing skid activity. they also should recognize my profile pic!, and use the header list

Roblox-DataCenter-Id: rbx0api.com
Roblox-Job-Signature: rbx0api.com
Rbxid-Digest: 860bf01602b80b8b152cce054d6e9458354eb810
Roblox-Request-IP-Address: localhost 
Roblox-Request-Account-Age: -000
Roblox-Proxied-IP: -000
X-Forwared-Host: localhost

**Comment by RoseMAgreement** [comment]
![e49af6ada70335bf55e9bec7d592aec2](https://user-images.githubusercontent.com/95501697/144663476-e7e0792a-bfbd-41d6-b49a-5222ec4404fc.png)

you honestly look like undertake here, the wwe superstar.

**Comment by RoseMAgreement** [comment]
like the way skid asks other skid for question 🙃 took screenshot this is actually funny .

**Comment by AcierP** [comment]
rosem you good bro?
