### ISSUE TITLE
enabling discussions

### ISSUE THREAD

**Issue by 4channel** [h0nde/tips-for-python-bot-creators#3]
check your repo settings
![image](https://user-images.githubusercontent.com/68159867/144894919-e6fb0fa2-d192-4a6b-95a6-febe8a44a105.png)
seems fitting

also would enjoy more stuff about organizing in classes and modules and the like, I never liked those

**Comment by h0nde** [comment]
I enabled discussions like you suggested, not sure if anybody will use them, but thanks for letting me know about them.

I don't think I'm experienced enough to be writing style guides, but you can look at popular Python repos and perhaps get an idea from them.
