### ISSUE TITLE
do you know any improvement with this code?

### ISSUE THREAD

**Issue by zentred** [h0nde/tips-for-python-bot-creators#4]
ik that there is improvements as shown in this repository, but without using completely different format like http.client, or using workers+threads, is there any improvement i can do with this code?

https://pastebin.com/gdQ0hA9g

**Comment by zentred** [comment]
this  doesnt actually do anything, but it's just the format i follow when making checkers.
also excuse any issues with how it looks. its cause of pastebin

**Comment by h0nde** [comment]
too many to list, but your main issue is still gonna be the usage of `requests`, and the fact that your code is not multiprocessing compatible.

**Comment by zentred** [comment]
ah so i really should just spend the time to learn multiprocessing and httpclient, ok gotcha 👍
